name: Clone Darktable Repo

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://qlandman:f71d81c03d7befac549f3c9ad9cef44383be9552@github.com/darktable-org/darktable.git"
        source_branch: "master"
        destination_repo: "https://qlandman:f71d81c03d7befac549f3c9ad9cef44383be9552@github.com/qlandman/darktable-win-build.git"
        destination_branch: "master"
       # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
